"""Second audit wave: ex commands, registers, macros, marks, gq/gw, blockwise,
folds, dot repeat, search atoms and :s flags."""
import json


def new_cases():
    T = "alpha beta gamma\ndelta epsilon\nzeta eta theta\niota kappa\nlambda mu"
    N = "10 apple\n2 banana\n33 cherry\n1 date\n2 banana\nb 7"
    W = "the quick brown fox jumps over the lazy dog and keeps running far away from here today"
    B = "abcdef\nghijkl\nmnopqr\nstuvwx"
    S = "foo(bar) baz\n  if (x) {\n    y;\n  }\nend"
    groups = [
     (N, 0, 0, [":sort<CR>", ":sort!<CR>", ":sort n<CR>", ":sort u<CR>", ":sort i<CR>",
                ":2,4sort<CR>", ":sort /\\d\\+ /<CR>", ":sort /\\d\\+/ r<CR>", ":sort nu<CR>",
                ":sort n!<CR>", ":sort x<CR>", ":sort /a/<CR>", ":sort /\\d\\+/<CR>",
                ":sort! n<CR>", ":sort ui<CR>", ":sort /\\a/ r<CR>"]),
     (T, 0, 0, [":normal Ax<CR>", ":%normal Ax<CR>", ":2,3normal dw<CR>",
                ":g/a/normal Ax<CR>", ":v/a/normal Ax<CR>", ":g!/a/d<CR>",
                ":g/a/s/a/X/g<CR>", ":g/e/m0<CR>", ":g/e/t.<CR>", ":g/e/t$<CR>",
                ":g/^/m0<CR>", ":g#a#d<CR>", ":g/a/normal! ddp<CR>", ":%norm Ihi <CR>",
                ":g/a/j<CR>", ":g/a/>|<CR>", ":g/a/y A<CR>:$put a<CR>",
                ":g/a/d A<CR>:$put a<CR>", ":v/a/d<CR>", ":g/a/-1j<CR>", ":g/a/co$<CR>",
                ":2,3g/a/d<CR>", ":g/a\\|e/d<CR>", ":g/a/s//X/<CR>",
                ":g/a/normal @q<CR>", ":g/a/normal dd<CR>", ":g/a/d|d<CR>",
                ":g/a/.,+1j<CR>", ":g/a/norm Ax<CR>:g/x/norm Ay<CR>"]),
     (T, 1, 2, [":r !echo hi<CR>", ":0r !echo hi<CR>", ":$r !echo hi<CR>",
                ":2,3!sort -r<CR>", "!!tr a-z A-Z<CR>", "!jtr a-z A-Z<CR>",
                ":.!tr a-z A-Z<CR>", ":%!sort -r<CR>", "!Gsort<CR>", ":1,2!echo x<CR>",
                ":.,+1!tac<CR>", "!iptac<CR>", "Vj!tac<CR>", ":r !printf 'a\\nb'<CR>",
                ":2r !echo hi<CR>", ":r !echo hi<CR>u", "2!!tac<CR>", ":.!echo -n x<CR>",
                "!!sort<CR>.", "!}sort -r<CR>"]),
     (T, 1, 2, [":t.<CR>", ":t0<CR>", ":t$<CR>", ":m0<CR>", ":m$<CR>", ":m+1<CR>",
                ":m-2<CR>", ":1,2m$<CR>", ":1,2t$<CR>", ":2,3m1<CR>", ":2,3m2<CR>",
                ":2,3m3<CR>", ":2,3m 0<CR>", ":2,3t 2<CR>", ":2,3t 1<CR>", ":%t.<CR>",
                ":%m0<CR>", ":1m2<CR>", ":2co0<CR>", ":2move 4<CR>", ":2,4m0<CR>",
                ":'<,'>m0<CR>", ":.,+2t0<CR>", ":2;+1m0<CR>", ":2m'a<CR>",
                ":2ma<CR>:4m'a<CR>", ":2,3>><CR>", ":2,3<<CR>", ":2,3> 2<CR>", ":>3<CR>",
                ":2,3j<CR>", ":2,3j!<CR>", ":j3<CR>", ":2,3d x<CR>:put x<CR>",
                ":2,3y<CR>:$put<CR>", ":2,3y<CR>:0put<CR>", ":2,3y<CR>:1put!<CR>",
                ":2d 2<CR>", ":2,3y x<CR>:3pu x<CR>", ":put =3<CR>", ":2,3co.<CR>",
                ":2k a<CR>:'a d<CR>", ":2,3center<CR>", ":2,3right 30<CR>",
                ":2,3left 3<CR>", ":2,3ce 10<CR>", ":2,3ri<CR>", ":le<CR>",
                ":2,3retab<CR>", ":2,3&&<CR>", ":2,3s/a/X/|3,4s/e/Y/<CR>",
                ":2,3d|1d<CR>", ":$<CR>x", ":3<CR>x", ":+<CR>x", ":-<CR>x", ":+2<CR>x",
                ":/zeta/<CR>x", ":?alpha?<CR>x", ":/zeta/;+1d<CR>", ":/zeta/,/kappa/d<CR>",
                ":\\/d<CR>", ":\\?d<CR>", ":\\&d<CR>", ":.,/lambda/d<CR>", ":2,/e/d<CR>",
                ":/e/+1d<CR>", ":/e//a/d<CR>", ":1,3d|put<CR>", ":2,3d _<CR>:put<CR>",
                ":%d|put! ='x'<CR>", ":2,3sort!<CR>", ":2;+1d<CR>", ":2,+1d<CR>",
                ":,+1d<CR>", ":;+1d<CR>", ":,d<CR>", ":2,d<CR>", ":,3d<CR>", ":,$d<CR>",
                ":3,2d<CR>", ":0d<CR>", ":0,2d<CR>", ":6d<CR>", ":1,6d<CR>", ":$+1d<CR>",
                ":-5d<CR>", ":2,3d 5<CR>", ":2d 1<CR>", ":2d 9<CR>", ":2,3 d<CR>",
                ":2,3 j 2<CR>", ":2,3y 2<CR>:$put<CR>", ":2,3y a 1<CR>:$put a<CR>",
                ":2,3copy 0|1d<CR>", ":2,3m 0|1d<CR>", ":2,3> |1d<CR>"]),
     (T, 1, 2, ["\"ayy\"Ayy\"ap", "\"ayw\"Ayw\"ap", "\"ayyj\"Ayw\"ap", "\"ayw\"Ayy\"ap",
                "\"add\"Add\"ap", "\"Ayy\"ap", "yy\"Ayy\"ap", "dddd\"1p\"2p",
                "dddd\"1pu.", "dd\"1p..", "dwdw\"-p", "dwjdd\"-p\"1p", "d}\"1p",
                "d/a<CR>\"1p", "d%\"1p", "dw\"1p", "yyjdd\"0p", "yyjdw\"0p",
                "ddjdd\"1P\"2P\"3P", "ddjdd\"1pu.u.", "\"_ddp", "\"_dwP",
                "yy\"xyw\"xp\"Xp", "yw:put<CR>", "yy:put<CR>", "yiwj\"0P",
                "\"ayiw\"byiw\"bp\"ap", "d3d\"1p\"2p\"3p", "3dd\"1p\"2p", "dj\"1p",
                "dj\"2p", "ddddddu\"1p..", "\"ayy\"aP", "\"ayy\"ap\"_dd\"ap", "x\"-p",
                "\"ayl\"Ayl\"Ayl\"ap", "\"ayw\"Ayy\"Ayw\"ap", "\"/p", "/eta<CR>\"/P",
                "\":p", ":s/a/b/<CR>\":p", "ixx<Esc>\".p", "ixx<Esc>j\".p",
                "yy\"=5*5<CR>p", "\"=3+4<CR>p", "\"=3+4<CR>P", "i<C-r>=3*4<CR><Esc>",
                "yiwo<C-r>0<Esc>", "yiwo<C-r><C-w><Esc>", "yyo<C-r>\"<Esc>",
                "yyo<C-r><C-p>\"<Esc>", "yyo<C-r><C-o>\"<Esc>", "yyA<C-r>\"<Esc>",
                "\"ayiwA<C-r>a<Esc>", "d)\"1p", "d(\"1p", "d{\"1p", "dG\"1p", "dgg\"1p",
                "dL\"1p", "dn\"1p", "d`a\"1p", "dwu\"-p", "ddu\"1p", "ddp\"1p",
                "5dd\"1p\"2p", "\"1p", "\"-p", "d/e/e<CR>\"-p", "d/e/e<CR>\"1p",
                "d/e/e+1<CR>\"1p", "dvjp", "dVwp", "d<C-v>jp", "c/e<CR>X<Esc>\"1p",
                "cjX<Esc>\"1p", "cwX<Esc>\"-p", "yyjcjX<Esc>\"0p", "\"ayy\"Ayw:put a<CR>",
                "\"ayw\"Ayy:put a<CR>", "\"ayw\"Ayw:put a<CR>", "\"ayy\"Ayy:put a<CR>",
                "\"ayy\"Ayy\"ap", "\"aywj\"Aywj\"ap", "\"AywP", "\"Aywp", "\"ayw\"AywP"]),
     (T, 0, 6, ["qaxq", "qaxq@a", "qaxq3@a", "qaxq@@", "qaxq@a@@", "qaxq:norm @a<CR>",
                "qaAx<Esc>jq@a", "qaAx<Esc>jq2@a", "qaAx<Esc>jq@a@@",
                "qaAx<Esc>jqu@a", "qaAx<Esc>jqqAAy<Esc>q@a", "qaxqqAxq@a",
                "qaxqqAjq@a", "qaIz<Esc>jq:2,3norm @a<CR>", "qa0xjq10@a", "qawxq@a",
                "qaddq@a", "qadwq\"ap", "qa0iX<Esc>q\"ap", "qa0iX<Esc>q:put a<CR>",
                "qaxq:let @b=@a<CR>@b", ":let @a=\"x\"<CR>@a", ":let @a='dd'<CR>@a",
                "\"ayy@a", "yy@\"", "ix<Esc>@.", "qa:s/a/b/<CR>q@a", "qa:s/a/b/<CR>jq@:",
                "qa/e<CR>q@a", "qa/e<CR>q@a@@", "qqq@q", "qaq@a",
                "qaxqjqbxq:2,3norm @a<CR>", "qaxq:2,3norm @a<CR>", "qaxqqbxq:%norm @a<CR>",
                "qa~q:%norm @a<CR>", "qa~q5@a", "qa~q5@a@@", "qa~q2@a@@", "qa~q2@a2@@",
                "qa~q@a:norm @@<CR>", "qa~q@aj@@", "qaq:norm @a<CR>", "qa~jq:norm 2@a<CR>",
                "qAxq", "qAxq@a", "qa~qqAxq\"ap", "qa~qqAxq:reg a<CR>", "qa~qqA~q@a",
                "qa~q:2norm @a<CR>", "qa~jq:2,3norm @a<CR>", "qa~q:2,3g/./norm @a<CR>"]),
     (T, 1, 2, ["majmb:'a,'bd<CR>", "ma`a", "majd'a", "majd`a", "majy'aP", "majy`aP",
                "ma:2<CR>'a", "majmb`a`b", "majmb'a''", "majmb'a``", "majmb`a``x",
                "jma0:'a<CR>x", "jmajjd'a", "majjmbgg:'a,'bd<CR>", "ma:delmarks a<CR>'a",
                "ma:delm!<CR>'ax", "majjmb:delm a-b<CR>`bx", "mA'Ax", "mAjmAk`Ax",
                "ixx<Esc>`[x", "ixx<Esc>`]x", "yiwj`[x", "yiwj`]x", "yyj'[x", "jyyk']x",
                "dwj`[x", "ddk`[x", "yw`]iX<Esc>", "xu`[x", "ixyz<Esc>gg`.x",
                "xj`.iZ<Esc>", "xjj'.iZ<Esc>", "xjj``iZ<Esc>", "Gggjj``iZ<Esc>",
                "G''iZ<Esc>", "jj:1<CR>``iZ<Esc>", "jjvj<Esc>gg`<iZ<Esc>",
                "jjvj<Esc>gg`>iZ<Esc>", "jjVj<Esc>gg`>iZ<Esc>", "jjVj<Esc>gg'<iZ<Esc>",
                "vj<Esc>gvd", "vj<Esc>jgvd", "vj<Esc>jgv<Esc>x", "Vj<Esc>gg:'<,'>d<CR>",
                "wvey$gvd", "ma0:normal `ax<CR>", "Axx<Esc>jgiy<Esc>", "Axx<Esc>jgIy<Esc>",
                "mamb`a`bd`a", "ma$mb:'a,'bd<CR>", "d'a", "]'", "['", "ma]'", "jma]`",
                "majjmb`a]'x", "majjmb`b['x", "majjmb`b[`x", "jmajjmbgg]`x",
                "jmajjmbG[`x", "jmajjmbgg2]'x", "ma:2,3m0<CR>'ax", "ma:2,3d<CR>'ax",
                "jma:1m$<CR>'ax", "jmaP`ax", "jmaOnew<Esc>'ax", "jmaddP'ax",
                "jma:s/e/\\r/<CR>'ax", "jmaJ'ax", "jmakJ'ax", "jmaddu'ax",
                "jmayyP'ax", "jma:1t.<CR>'ax", "jmaggdd'ax", "jmaggddu'ax",
                "jmaggOx<Esc>'ax", "jmakddjdd'ax", "jmaggyyGp'ax", "mazfj'ax"]),
     (W, 0, 0, [":set tw=20<CR>gqq", ":set tw=20<CR>gqqx", ":set tw=30<CR>gqip",
                ":set tw=20<CR>gwwix<Esc>", ":set tw=20<CR>gwwx", ":set tw=20<CR>gwq",
                ":set tw=20<CR>gwgw", ":set tw=20<CR>gqgqx", ":set tw=20<CR>Vgq",
                ":set tw=20<CR>gqG", ":set tw=20<CR>gqj", ":set tw=20<CR>gq$",
                ":set tw=20<CR>gqw", ":set tw=20<CR>gqaw", ":set tw=20<CR>w10lgqq",
                ":set tw=20<CR>gqq`[x", ":set tw=20<CR>gqq`]x", ":set tw=20<CR>gwwgg`[x",
                ":set tw=20<CR>gww`]x", ":set tw=20<CR>gqq'[x", ":set tw=20<CR>$gqq",
                ":set tw=20<CR>A xx<Esc>",
                ":set tw=20<CR>A xx yy zz aa bb cc dd ee ff<Esc>",
                ":set tw=20<CR>ifoo bar baz foo bar baz foo bar baz<Esc>",
                ":set tw=20<CR>$a foo bar baz<Esc>", "gqq", "gqqx", ":set tw=20<CR>3gqq",
                ":set tw=20<CR>:s/the/xxxxxxxxxxxxxxxxxxxxxxxx/<CR>gqq",
                ":set tw=20<CR>gqqu", ":set tw=20<CR>gqqgg.", ":set tw=20<CR>gqqj.",
                ":set tw=20<CR>gqq:2,3j<CR>gqq", ":set tw=20<CR>:2,3j<CR>", ":set tw=20<CR>Vgqgv<Esc>",
                ":set tw=10<CR>gqq", ":set tw=1<CR>gqq", ":set tw=5<CR>gqq",
                ":set tw=20<CR>gqq:1,3>><CR>", ":set tw=20<CR>gqqgg>>gqq"]),
     ("  indented text that is long enough to wrap over multiple lines yes\n  second line\n\n- bullet one is long and wraps here ok\n  next",
      0, 0, [":set tw=20<CR>gqG", ":set tw=20<CR>gqip", ":set tw=20<CR>gqap",
             ":set tw=20<CR>gqj", ":set tw=20<CR>gqq", ":set tw=20 ai<CR>gqq",
             ":set tw=20<CR>gwip", ":set tw=20<CR>4Ggqj", ":set tw=20<CR>gqip`]x",
             ":set tw=20<CR>gqip']x", ":set tw=20 fo+=n<CR>4Ggqj",
             ":set tw=20 fo+=2<CR>gqap", ":set tw=20 fo-=j<CR>gqG",
             ":set tw=15<CR>3Ggqj", ":set tw=20 fo+=w<CR>gqG"]),
     (B, 0, 1, ["<C-v>jld", "<C-v>jly", "<C-v>jlyP", "<C-v>jlyGp", "<C-v>jl$d",
                "<C-v>j$y$p", "<C-v>jlcX<Esc>", "<C-v>j$AX<Esc>", "<C-v>jlAX<Esc>",
                "<C-v>jlIX<Esc>", "<C-v>jl$IX<Esc>", "<C-v>jlrX", "<C-v>jlU", "<C-v>jlu",
                "<C-v>jl~", "<C-v>jlJ", "<C-v>jlgJ", "<C-v>jl>", "<C-v>jl<", "<C-v>jl2>",
                "<C-v>jlo<Esc>x", "<C-v>jlOd", "<C-v>jlOOd", "<C-v>jlood", "<C-v>jlsX<Esc>",
                "<C-v>jlCX<Esc>", "<C-v>jlSX<Esc>", "<C-v>jlRX<Esc>", "<C-v>jlD",
                "<C-v>jlX", "<C-v>jlY", "<C-v>jlYGp", "<C-v>jlyGP", "<C-v>jlyG$p",
                "<C-v>jlyj$p", "<C-v>jlyjp", "<C-v>jlyjP", "<C-v>jlyjgp", "<C-v>jlyjgP",
                "<C-v>jlygvd", "<C-v>jlyjvp", "<C-v>jlyjVp", "<C-v>jlyjvlp",
                "<C-v>jlyjjvp", "<C-v>jlyjl<C-v>jp", "<C-v>jlyjl<C-v>jjp",
                "<C-v>jlyjl<C-v>jlp", "yyj<C-v>jlp", "yiwj<C-v>jlp", "<C-v>jl:s/./X/<CR>",
                "<C-v>jl:s/\\%V./X/<CR>", "<C-v>jl:normal Ax<CR>", "<C-v>jl:normal x<CR>",
                "<C-v>jl\"ay\"aP", "<C-v>jld.", "<C-v>jld3.", "<C-v>jlcX<Esc>j.",
                "<C-v>jlAX<Esc>jj.", "<C-v>jlAX<Esc>.", "<C-v>jlIX<Esc>jj.",
                "<C-v>jlrXj.", "<C-v>jlrX.", "<C-v>jl<C-v>", "<C-v>jlv", "<C-v>jlV",
                "<C-v>jl<Esc>gvd", "<C-v>jl<Esc>gvAX<Esc>", "<C-v>jl$<Esc>gvd",
                "<C-v>j$<Esc>gvd", "<C-v>$jd", "<C-v>$jy$p", "<C-v>$jAX<Esc>",
                "<C-v>$jIX<Esc>", "<C-v>$jcX<Esc>", "<C-v>jj$AX<Esc>",
                "<C-v>jjlAX<Esc>", "<C-v>jjhAX<Esc>", "<C-v>jjhd", "<C-v>jjhy$p",
                "<C-v>jj0IX<Esc>", "l<C-v>jjhIX<Esc>", "<C-v>jjIX<Esc>u",
                "<C-v>jjAX<Esc>u", "<C-v>jjcX<Esc>u", "<C-v>jjdu", "<C-v>jlIab<Esc>",
                "<C-v>jlAab<Esc>", "<C-v>jlcab<Esc>", "<C-v>jlIa<CR>b<Esc>",
                "<C-v>jlAa<CR>b<Esc>", "<C-v>jlIa<BS>b<Esc>", "<C-v>jlIa<C-w>b<Esc>",
                "<C-v>jlIa<C-u>b<Esc>", "<C-v>jlI<BS>X<Esc>", "<C-v>jl$Aa<BS>b<Esc>",
                "<C-v>jlIa<Left>b<Esc>", "<C-v>jlIa<C-r>\"b<Esc>", "<C-v>jlIa<C-t>b<Esc>",
                "<C-v>jlI<C-t>b<Esc>", "<C-v>jlIa<Tab>b<Esc>", "<C-v>jlIa<Del>b<Esc>",
                "<C-v>jlIa<C-c>", "<C-v>jlgIX<Esc>", "<C-v>jl<C-a>", "<C-v>jlg<C-a>",
                "<C-v>jlg<C-x>", "<C-v>jlo$d", "<C-v>j$o<Esc>x", "<C-v>jjjd",
                "<C-v>3jd", "<C-v>3jlld", "<C-v>3j5ld", "<C-v>3j5lAX<Esc>",
                "<C-v>3j5lIX<Esc>", "<C-v>G$AX<Esc>", "<C-v>Gld", "<C-v>Gc12<Esc>",
                "<C-v>wd", "<C-v>ed", "<C-v>bd", "<C-v>fcd", "<C-v>jfcd", "<C-v>j2ld",
                "<C-v>j2lOd", "<C-v>j2lod", "<C-v>j2lyj$p", "<C-v>j2lyjP",
                "<C-v>j2lyjlP", "<C-v>j2lyjllllp", "<C-v>j2lyjlllllp", "<C-v>j2lyG$p",
                "<C-v>j2lyG$P", "<C-v>j2lyGgp", "<C-v>j2lyGgP", "<C-v>j2ly3p",
                "<C-v>j2lyjj3p", "<C-v>j2lyjj3gp", "<C-v>j2lyjjvp", "<C-v>j2lyjjvlp",
                "<C-v>j2lyjjvhp", "<C-v>j2lyjjvhpu", "<C-v>j2lyjjvhp`[x",
                "<C-v>j2lyjjvhp`]x", "<C-v>j2lyp`[x", "<C-v>j2lyp`]x", "<C-v>j2lyP`]x",
                "<C-v>j2lygp`]x", "<C-v>j2lyp:'[,']d<CR>", "<C-v>j2ly:2put<CR>",
                "<C-v>j2ly:2put!<CR>", "<C-v>j2ly:$put<CR>", "<C-v>j2ly:put<CR>",
                "<C-v>j2ly:normal p<CR>", "<C-v>j2ly:normal $p<CR>"]),
     ("a\tb\nabcdefgh\nxyz", 0, 0, ["<C-v>jld", "l<C-v>jd", "<C-v>jlAX<Esc>",
                "<C-v>jlIX<Esc>", "l<C-v>jlcX<Esc>", "l<C-v>jly$p", "l<C-v>jlrX",
                "<C-v>jlyGp", "ll<C-v>jd", "<C-v>j4ld", "<C-v>j4lAX<Esc>",
                "<C-v>j5lAX<Esc>", "<C-v>j4lIX<Esc>", "l<C-v>jIX<Esc>", "l<C-v>jAX<Esc>",
                "l<C-v>jjAX<Esc>", "l<C-v>jjd", "l<C-v>jjy$p", "l<C-v>jjc12<Esc>",
                "l<C-v>jjr1", "l<C-v>jj>", "l<C-v>jj<", "l<C-v>jjJ", "l<C-v>jj~",
                "l<C-v>jj$d", "l<C-v>jj$AX<Esc>", ":set sw=2<CR>l<C-v>jj>",
                ":set noet<CR>l<C-v>jj>", ":set noet<CR><C-v>jj>",
                ":set noet sw=8<CR><C-v>jj>", ":set noet sw=8<CR>>>",
                ":set noet<CR>l<C-v>jjIX<Esc>", ":set noet<CR>l<C-v>jjy$p",
                ":set noet<CR>l<C-v>jjyGp", "<C-v>jlp", "<C-v>jy$p", "ll<C-v>jyP"]),
     (S, 1, 3, ["zfj", "zfjzo", "zfjzc", "zfjdd", "zfjjdd", "zfjzoj", "zfjzcj",
                "zfjjzcdd", "zfjyy", "zfjyyP", "zfjyyjp", "zfjzfj", "zfjzd", "zfjzE",
                "zfjzfjzo", "zfjzR", "zfjzM", "zfjzn", "zfjzN", "zfjzi", "zfjza",
                "zfjzA", "zfjzv", "zfjzx", "zfjzX", "zfjzj", "zfjzk", "zfjggzj",
                "zfjggzjx", "zfjGzkx", "zfjgg[zx", "zfjgg]zx", "zfjzo[zx", "zfjzo]zx",
                ":2,3fold<CR>", ":2,3fold<CR>dd", ":2,3fold<CR>j", ":2,3fold<CR>jdd",
                ":2,3fold<CR>k", ":2,3fold<CR>kdd", ":2,3fold<CR>ggjdd",
                ":2,3fold<CR>ggjjdd", ":2,3fold<CR>ggjjx", ":2,3fold<CR>ggjjyyP",
                ":2,3fold<CR>ggjjyyjjp", ":2,3fold<CR>ggjj>>", ":2,3fold<CR>ggjjJ",
                ":2,3fold<CR>ggjjcc<Esc>", ":2,3fold<CR>ggjjrx", ":2,3fold<CR>ggjj~",
                ":2,3fold<CR>ggjjg~~", ":2,3fold<CR>ggjjgUU", ":2,3fold<CR>ggjj:s/./X/<CR>",
                ":2,3fold<CR>ggjj:normal x<CR>", ":2,3fold<CR>ggjjzoj",
                ":2,3fold<CR>ggjjzojdd", ":2,3fold<CR>ggjjzozcdd",
                ":2,3foldopen<CR>jdd", ":2,3foldclose<CR>jdd", ":%foldopen<CR>jdd",
                ":%foldclose<CR>jdd", ":2,3fold<CR>:%folddoc d<CR>",
                ":2,3fold<CR>:%folddoopen d<CR>", ":2,3fold<CR>:%folddoclosed d<CR>",
                ":2,3fold<CR>zo:%folddoclosed d<CR>", ":2,3fold<CR>zo:%folddoopen s/./X/<CR>",
                ":2,3fold<CR>:%folddoclosed s/./X/<CR>", "zfjzojzfjzcggjdd",
                "zf2jzo", "zfapzo", "zfipdd", "zF", "2zF", "zfjzojzc", "zfjjzfkzc"]),
     (T, 1, 2, ["g??", "g?g?", "g?w", "g?$", "g?ip", "vg?", "Vg?", "g?iw.", "g?w.",
                "g?wj.", "g?2w", "2g?w", "2g??", "3g??", "g??u", "g??u<C-r>"]),
     (T, 1, 2, ["ci(X<Esc>", "ciwX<Esc>.", "cawX<Esc>j.", "cwX<Esc>j.", "cwX<Esc>j0.",
                "cwX<Esc>3.", "cwX<Esc>j3.", "2cwX<Esc>j.", "2cwX<Esc>j3.", "dw2.",
                "d2w.", "d2w3.", "3dw2.", "2dd.", "2dd3.", "3dd2.", "3ddj.", "x3.",
                "3x2.", "3~2.", "3rx.", "3rxj.", "3J2.", "J3.", "3>>.", "3>>j.",
                ">2j.", ">2j3.", "2>j3.", "2>>.", "3A!<Esc>.", "3A!<Esc>2.", "3o!<Esc>2.",
                "3s!<Esc>.", "C!<Esc>j.", "Rab<Esc>j.", "3Rab<Esc>.", "Rab<Esc>2.",
                "gUiwj0.", "gUj.", "gUgUj.", "5<C-a>2.", "dd.u.", "dd.uu.", "dd.u<C-r>.",
                "xu.u.", "x..u..", "xxxuuu...", "xxxuuuu...", "xxxuuuu<C-r><C-r>.",
                "yyp.", "yyP.", "yyp3.", "yy3p.", "3yyp.", "3yyjp.", "ywP.", "ywp2.",
                "ywj.", "\"ayy\"ap.", "\"ayy\"Ayy\"ap.", "dd\"1p.", "dd\"1p..", "dd\"1pu.",
                "dwu.", "xp.", "ddp.", "ddjp.", "ddkP.", "~~.", "g~~.", "g~~j.",
                "cc!<Esc>j.", "cc!<Esc>2.", "cip!<Esc>.", "cip!<Esc>jj.", "ci(!<Esc>.",
                "ct!X<Esc>.", "cfe!<Esc>.", "cfe!<Esc>;.", "dfe;.", "dfe,.", "dte;.",
                "d/e<CR>.", "d/e<CR>n.", "dn.", "d?e<CR>.", "dgn", "cgnX<Esc>.", "/e<CR>cgnX<Esc>..",
                "/e<CR>dgn.", "/e<CR>dgN.", "/e<CR>cgNX<Esc>.", "*cgnX<Esc>.", "#cgnX<Esc>.",
                "/e<CR>gnd", "/e<CR>gNd", "/e<CR>gnc<Esc>", "/e<CR>vgnd", "/e<CR>vgngnd"]),
     (T, 0, 0, ["/a/e<CR>", "/a/e+1<CR>", "/a/b+1<CR>", "/a/s-1<CR>", "/a/;/e<CR>",
                "/a/;/e/e<CR>", "/a\\nd<CR>", "/\\n<CR>", "/\\n\\n<CR>", "/a$<CR>",
                "/^d<CR>", "/\\<e<CR>", "/\\ce<CR>", "/\\CE<CR>", "/E\\c<CR>", "/\\vE|z<CR>",
                "/\\v(a)\\1<CR>", "/\\%2l<CR>", "/\\%>2l.<CR>", "/\\%<2l.<CR>", "/\\%3c.<CR>",
                "/\\%>3c.<CR>", "/\\%<3c.<CR>", "/\\%2v.<CR>", "/\\%V<CR>", "/\\%^<CR>",
                "/\\%$<CR>", "/\\%#<CR>", "ma/\\%'a<CR>", "ma/\\%>'a<CR>", "ma/\\%<'a<CR>",
                "/\\%[abc]<CR>", "/gam\\%[ma]<CR>", "/\\%d97<CR>", "/\\%x61<CR>",
                "/\\%u0061<CR>", "/\\%o141<CR>", "/a\\{-1,}<CR>", "/a\\{2}<CR>", "/a\\=<CR>",
                "/a\\?<CR>", "/a\\@=<CR>", "/a\\@!<CR>", "/\\(a\\)\\@<=l<CR>",
                "/\\(a\\)\\@<!l<CR>", "/\\(a\\)\\@>l<CR>", "/\\(alp\\)\\@<=h<CR>",
                "/\\_^d<CR>", "/a\\_$<CR>", "/\\_.<CR>", "/\\_s\\+<CR>", "/\\_[a-z]\\+<CR>",
                "/[[:alpha:]]\\+<CR>", "/[[:digit:]]<CR>", "/[[:upper:]]<CR>",
                "/[[:space:]]\\+<CR>", "/[[:punct:]]<CR>", "/[[:alnum:]]\\+<CR>",
                "/[[:lower:]]\\+<CR>", "/[[:blank:]]<CR>", "/[[:xdigit:]]\\+<CR>",
                "/[[:graph:]]\\+<CR>", "/[[:print:]]\\+<CR>", "/[a-c]\\+<CR>",
                "/[^a-c ]\\+<CR>", "/[\\d97]<CR>", "/[\\x61]<CR>", "/[\\u0061]<CR>",
                "/[\\o141]<CR>", "/[\\\\]<CR>", "/[\\]]<CR>", "/[\\^]<CR>", "/[a\\-c]<CR>",
                "/\\h\\+<CR>", "/\\H\\+<CR>", "/\\a\\+<CR>", "/\\A\\+<CR>", "/\\l\\+<CR>",
                "/\\L\\+<CR>", "/\\u<CR>", "/\\U\\+<CR>", "/\\w\\+<CR>", "/\\W\\+<CR>",
                "/\\i\\+<CR>", "/\\I\\+<CR>", "/\\k\\+<CR>", "/\\K\\+<CR>", "/\\f\\+<CR>",
                "/\\F\\+<CR>", "/\\p\\+<CR>", "/\\P\\+<CR>", "/\\s\\+<CR>", "/\\S\\+<CR>",
                "/\\d<CR>", "/\\D\\+<CR>", "/\\x\\+<CR>", "/\\X\\+<CR>", "/\\o<CR>",
                "/\\O\\+<CR>", "/\\t<CR>", "/~<CR>", "/\\~<CR>", "/a.\\{-}a<CR>",
                "/\\v<a><CR>", "/\\v<(a|e)>.*<(a|e)><CR>", "/\\v(a|e)+<CR>",
                "/\\v[ae]{2}<CR>", "/\\v[ae]{-1,}<CR>", "/\\v(\\w)\\1<CR>",
                "/\\v(\\w+) \\1<CR>", "/\\v%(a)@<=l<CR>", "/\\v(a)@<!l<CR>",
                "/\\v(a)@!l<CR>", "/\\v(a)@=l<CR>", "/\\v(a)@>l<CR>", "/\\v&<CR>",
                "/\\v=<CR>", "/\\v?<CR>", "/\\M.<CR>", "/\\M.*<CR>", "/\\M\\.\\*<CR>",
                "/\\M^a<CR>", "/\\Ma$<CR>", "/\\M[a]<CR>", "/\\M\\[a]<CR>", "/\\V.<CR>",
                "/\\V\\.<CR>", "/\\V^a<CR>", "/\\Va$<CR>", "/\\V\\^a<CR>", "/\\V\\<a<CR>",
                "/\\V\\(a\\)<CR>", "/\\V(a)<CR>", "/\\V\\(a\\)\\1<CR>", "/\\V\\(a\\)\\+<CR>",
                "/\\V\\n<CR>", "/\\Va\\|e<CR>", "/\\Va\\|e\\|l<CR>", "/a\\|e<CR>",
                "/\\%(a\\|e\\)<CR>", "/\\(a\\|e\\)\\{2}<CR>", "/a\\&.<CR>",
                "/.*a\\&.*e<CR>", "/\\zsa<CR>", "/a\\zs.<CR>", "/a\\ze.<CR>", "/a\\zel<CR>",
                "/\\zea<CR>", "/\\(\\zea\\)<CR>", "/a\\zsl\\zep<CR>",
                "/\\v<(.)\\zs.*\\1><CR>", "/\\%d97\\+<CR>", "/\\.<CR>", "/\\*<CR>",
                "/\\/<CR>", "/\\\\<CR>", "/\\]<CR>", "/\\[<CR>", "/\\^<CR>", "/\\$<CR>",
                "/^<CR>", "/$<CR>", "/a^<CR>", "/a$b<CR>", "/\\(^a\\)<CR>", "/\\(a$\\)<CR>",
                "/\\(^\\)a<CR>", "/\\|a<CR>", "/a\\|<CR>", "/\\|<CR>", "/\\(\\)<CR>",
                "/\\%(\\)<CR>", "/*a<CR>", "/\\(*a\\)<CR>", "/^*a<CR>", "/a**<CR>",
                "/a\\+\\+<CR>", "/a*\\{2}<CR>"]),
     (T, 0, 0, [":s/a/X/g<CR>", ":s/a/X/gc<CR>y", ":s/a/X/gc<CR>yn", ":s/a/X/gc<CR>nyy",
                ":s/a/X/gc<CR>a", ":s/a/X/gc<CR>l", ":s/a/X/gc<CR>q", ":s/a/X/gc<CR>yq",
                ":s/a/X/gc<CR><Esc>", ":%s/a/X/gc<CR>yyyyyy", ":%s/a/X/gc<CR>nnnnnn",
                ":%s/a/X/gc<CR>yyyynn", ":%s/a/X/gc<CR>yyyyl", ":%s/a/X/gc<CR>yyyya",
                ":%s/a/X/gc<CR>yyyyq", ":%s/a/X/gc<CR>nyyyyy", ":%s/a/X/gc<CR>yyyyyyyyyy",
                ":%s/a/X/gc<CR>yu", ":%s/a/X/gc<CR>yyyyyyyyyyyyyyu", ":%s/a/X/gcu",
                ":%s/a/X/gn<CR>", ":%s/a/X/n<CR>", ":%s/a/X/gn<CR>x", ":%s/a/X/n<CR>x",
                ":s/a/X/&<CR>", ":s/a/X/&&<CR>", ":s/a/X/g|s//Y/&<CR>",
                ":s/a/X/g<CR>:s/e/Y/&<CR>", ":s/a/X/g<CR>j:s/e/Y/&<CR>", ":s/a/X/g<CR>j:&&<CR>",
                ":s/a/X/g<CR>j:&<CR>", ":s/a/X/g<CR>j:&g<CR>", ":s/a/X/<CR>j:&g<CR>",
                ":s/a/X/<CR>j:&&<CR>", ":s/a/X/<CR>j&", ":s/a/X/g<CR>j&", ":s/a/X/<CR>jg&",
                ":s/a/X/g<CR>jg&", ":s/a/X/<CR>:%&g<CR>", ":s/a/X/<CR>:%&&<CR>",
                ":s/a/X/<CR>:%~<CR>", ":s/a/X/<CR>:%&r<CR>", ":s/a/X/<CR>/e<CR>:%~<CR>",
                ":s/a/X/<CR>/e<CR>:%&r<CR>", ":s/a/X/<CR>/e<CR>:s//Y/<CR>",
                ":s/a/X/<CR>/e<CR>:%s//Y/g<CR>", ":s/a/X/<CR>/e<CR>:%s//~/g<CR>",
                ":s/a/X/<CR>:%s/e/~/g<CR>", ":s/a/X/<CR>:%s/e/~~/g<CR>",
                ":s/a/X/<CR>:%s/e/\\~/g<CR>", ":%s/e/&&/g<CR>", ":%s/e/\\&/g<CR>",
                ":%s/e/\\\\/g<CR>", ":%s/e/\\//g<CR>", ":%s/e/\\n/g<CR>", ":%s/e/\\r/g<CR>",
                ":%s/e/\\t/g<CR>", ":%s/e/\\0/g<CR>", ":%s/\\(e\\)\\(p\\)/\\2\\1/g<CR>",
                ":%s/\\v(e)(p)/\\2\\1/g<CR>", ":%s/\\(e\\)\\(p\\)/\\9\\1/g<CR>",
                ":%s/e/\\u&/g<CR>", ":%s/e/\\U&/g<CR>", ":%s/\\(e\\)\\(p\\)/\\U\\1\\E\\2/g<CR>",
                ":%s/\\(e\\)\\(p\\)/\\U\\1\\e\\2/g<CR>", ":%s/\\(e\\)\\(p\\)/\\u\\1\\l\\2/g<CR>",
                ":%s/\\(e\\)\\(p\\)/\\U\\l\\1\\2/g<CR>", ":%s/\\(e\\)\\(p\\)/\\L\\u\\1\\2/g<CR>",
                ":%s/.*/\\L\\u&/<CR>", ":%s/\\w\\+/\\u&/g<CR>", ":%s/\\<./\\u&/g<CR>",
                ":%s/\\v<(\\w)(\\w*)>/\\u\\1\\L\\2/g<CR>", ":%s/a/\\=1+1/g<CR>",
                ":%s/a/\\=submatch(0)/g<CR>", ":%s/a/\\=line('.')/g<CR>",
                ":%s/a/\\=toupper(submatch(0))/g<CR>", ":%s/\\w\\+/\\=strlen(submatch(0))/g<CR>",
                ":%s/a/\\=\"x\\ry\"/g<CR>", ":%s/a/\\=['x','y']/g<CR>",
                ":%s/a/\\=repeat('x', 3)/g<CR>", ":%s/a/\\=col('.')/g<CR>",
                ":%s/a/X/ge<CR>", ":%s/z/X/e<CR>", ":%s/z/X/<CR>x", ":%s/a/X/i<CR>",
                ":%s/A/X/i<CR>", ":%s/A/X/I<CR>", ":%s/a/X/gi<CR>", ":%s/a/X/gg<CR>",
                ":%s/a/X/g2<CR>", ":%s/a/X/2<CR>", ":s/a/X/ 2<CR>", ":s/a/X/g 2<CR>",
                ":s/a/X/ 4<CR>", ":s/a/X/ 5<CR>", ":s/a/X/ 500<CR>", ":%s/a/X/g 3<CR>",
                ":%s a X g<CR>", ":%s,a,X,g<CR>", ":%s;a;X;g<CR>", ":%s#a#X#g<CR>",
                ":%s!a!X!g<CR>", ":%s|a|X|g<CR>", ":%s+a+X+g<CR>", ":%s_a_X_g<CR>",
                ":%s-a-X-g<CR>", ":%s\"a\"X\"g<CR>", ":%s'a'X'g<CR>", ":%s&a&X&g<CR>",
                ":%s.a.X.g<CR>", ":%s%a%X%g<CR>", ":%s$a$X$g<CR>", ":%s=a=X=g<CR>",
                ":%s?a?X?g<CR>", ":%s^a^X^g<CR>", ":%s~a~X~g<CR>", ":%sxaxXxg<CR>",
                ":%s1a1X1g<CR>", ":%s a b<CR>", ":%s/a/b/g|s/e/f/g<CR>",
                ":%s/a/b/|s/e/f/<CR>", ":%s/a/b/g|norm x<CR>", ":%s/a/b/g|$d<CR>",
                ":%s/a/\\|b/g<CR>", ":%s/a/b|c/g<CR>", ":%s/a/b\\|c/g<CR>",
                ":%s/a\\|e/b/g<CR>", ":%s/\\v(a|e)/<\\1>/g<CR>", ":%s/\\v(a|e)/\\<\\1\\>/g<CR>",
                ":%s/a/\\<&\\>/g<CR>", ":%s/a/\\\\&/g<CR>", ":%s/a/\\\\\\&/g<CR>",
                ":%s/a/\\\\n/g<CR>", ":%s/a/\\x/g<CR>", ":%s/a/\\./g<CR>",
                ":%s/a/\\a/g<CR>", ":%s/a/\\b/g<CR>", ":%s/a/\\z/g<CR>"]),
    ]
    cases = []
    for text, line, col, keys in groups:
        for k in keys:
            cases.append({"text": text, "line": line, "col": col, "keys": k})
    return cases


if __name__ == "__main__":
    c = new_cases()
    json.dump(c, open("wb.json", "w"))
    print(len(c))
